In [25]:
import pandas as pd
import numpy as np 
import warnings
warnings.filterwarnings('ignore')

print("Libraries loaded successfully")
print(f"pandas version: {pd.__version__}")
print(f"numpy version: {np.__version__}")

Libraries loaded successfully
pandas version: 3.0.3
numpy version: 2.4.4

In [26]:
#load the dataset
#'..' means go one folder up from notebooks/ to reach the project roots
#then go into data/raw/ to find the file

df = pd.read_excel(
    '../data/raw/NFHS_5_India_Districts_Factsheet_Data.xls',
    engine= 'xlrd',
    header=0
)

print("Dataset loaded successfully!")
print(f"shape: {df.shape}")

Dataset loaded successfully!
shape: (707, 109)

In [27]:
#see the first 5 rows
#like opening the first page of register

df.head

<bound method NDFrame.head of                  District Names                   State/UT  \
0                      Nicobars  Andaman & Nicobar Islands
1       North & Middle Andaman   Andaman & Nicobar Islands
2                South Andaman   Andaman & Nicobar Islands
3                   Srikakulam              Andhra Pradesh
4                 Vizianagaram              Andhra Pradesh
..                          ...                        ...
702  South Twenty Four Pargana                 West Bengal
703          Paschim Medinipur                 West Bengal
704            Purba Medinipur                 West Bengal
705         Paschim Barddhaman                 West Bengal
706           Purba Barddhaman                 West Bengal

     Number of Households surveyed  \
0                              882
1                              874
2                              868
3                              874
4                              902
..                             ...
702                            917
703                            910
704                            873
705                            912
706                            915

     Number of Women age 15-49 years interviewed  \
0                                            764
1                                            789
2                                            844
3                                            780
4                                            853
..                                           ...
702                                         1089
703                                         1002
704                                          957
705                                         1190
706                                         1088

     Number of Men age 15-54 years interviewed  \
0                                          125
1                                          108
2                                          134
3                                          100
4                                          134
..                                         ...
702                                        148
703                                        137
704                                        131
705                                        184
706                                        163

     Female population age 6 years and above who ever attended school (%)  \
0                                                78.01
1                                                82.66
2                                                84.68
3                                                59.99
4                                                55.95
..                                                 ...
702                                              80.93
703                                              72.10
704                                              83.04
705                                              74.84
706                                              71.15

     Population below age 15 years (%)  \
0                                22.98
1                                19.82
2                                20.95
3                                20.71
4                                20.56
..                                 ...
702                              25.49
703                              23.43
704                              23.85
705                              22.32
706                              22.21

      Sex ratio of the total population (females per 1,000 males)  \
0                                               973.31
1                                               949.82
2                                               967.48
3                                              1139.51
4                                              1114.35
..                                                 ...
702                                            1054.81
703                                            1088.57
704                                            1031.40
705                                             977.46
706                                            1067.12

     Sex ratio at birth for children born in the last five years (females per 1,000 males)  \
0                                               927.41
1                                               844.43
2                                               934.92
3                                              1162.58
4                                               898.03
..                                                 ...
702                                            1099.04
703                                            1005.04
704                                             777.38
705                                             786.93
706                                             877.10

     Children under age 5 years whose birth was registered with the civil authority (%)  \
0                                                98.01
1                                               100.00
2                                                96.53
3                                                94.96
4                                                95.42
..                                                 ...
702                                              97.56
703                                              99.32
704                                              99.25
705                                              97.70
706                                              99.61

     ...  \
0    ...
1    ...
2    ...
3    ...
4    ...
..   ...
702  ...
703  ...
704  ...
705  ...
706  ...

    Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)  \
0                                                32.86
1                                                22.62
2                                                17.88
3                                                14.37
4                                                14.83
..                                                 ...
702                                              13.03
703                                              10.66
704                                              11.92
705                                              14.45
706                                              11.50

     Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)  \
0                                                11.06
1                                                 5.97
2                                                 6.09
3                                                 5.51
4                                                 6.43
..                                                 ...
702                                               4.28
703                                               4.33
704                                               4.40
705                                               3.67
706                                               3.82

     Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)  \
0                                                46.97
1                                                32.20
2                                                26.90
3                                                22.89
4                                                25.13
..                                                 ...
702                                              19.13
703                                              18.98
704                                              21.31
705                                              20.67
706                                              18.39

     Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%)  \
0                                                13.35
1                                                 1.70
2                                                 1.32
3                                                 1.04
4                                                 4.90
..                                                 ...
702                                               0.00
703                                               0.00
704                                               0.00
705                                               0.70
706                                               0.19

     Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%)  \
0                                                13.16
1                                                 0.25
2                                                 0.67
3                                                 0.23
4                                                 0.63
..                                                 ...
702                                               0.00
703                                               0.00
704                                               0.19
705                                               1.30
706                                               0.10

     Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)  \
0                                                 5.37
1                                                15.84
2                                                 8.00
3                                                 3.76
4                                                 7.33
..                                                 ...
702                                               0.20
703                                               0.00
704                                               0.46
705                                               0.40
706                                               0.00

     Women age 15 years and above who use any kind of tobacco (%)  \
0                                                63.46
1                                                46.77
2                                                19.60
3                                                 7.09
4                                                11.41
..                                                 ...
702                                               6.28
703                                              18.83
704                                              12.93
705                                              11.79
706                                               9.93

    Men age 15 years and above who use any kind of tobacco (%)  \
0                                                76.79
1                                                70.47
2                                                50.76
3                                                21.32
4                                                21.47
..                                                 ...
702                                              49.76
703                                              50.48
704                                              40.11
705                                              40.23
706                                              50.06

     Women age 15 years and above who consume alcohol (%)  \
0                                                29.59
1                                                 5.08
2                                                 1.72
3                                                 0.55
4                                                 0.80
..                                                 ...
702                                               0.39
703                                               1.46
704                                               1.97
705                                               0.83
706                                               1.17

     Men age 15 years and above who consume alcohol (%)
0                                                64.49
1                                                45.26
2                                                32.81
3                                                28.26
4                                                32.30
..                                                 ...
702                                              16.54
703                                              20.81
704                                              14.80
705                                              14.58
706                                              22.94

[707 rows x 109 columns]>

In [28]:
#see all column names
#like reading the header row of the register

print(df.columns.tolist())

['District Names', 'State/UT', 'Number of Households surveyed', 'Number of Women age 15-49 years interviewed', 'Number of Men age 15-54 years interviewed', 'Female population age 6 years and above who ever attended school (%)', 'Population below age 15 years (%)', ' Sex ratio of the total population (females per 1,000 males)', 'Sex ratio at birth for children born in the last five years (females per 1,000 males)', 'Children under age 5 years whose birth was registered with the civil authority (%)', 'Deaths in the last 3 years registered with the civil authority (%)', 'Population living in households with electricity (%)', 'Population living in households with an improved drinking-water source1 (%)', 'Population living in households that use an improved sanitation facility2 (%)', 'Households using clean fuel for cooking3 (%)', 'Households using iodized salt (%)', 'Households with any usual member covered under a health insurance/financing scheme (%)', 'Children age 5 years who attended pre-primary school during the school year 2019-20 (%)', 'Women (age 15-49) who are literate4 (%)', 'Women (age 15-49)  with 10 or more years of schooling (%)', 'Women age 20-24 years married before age 18 years (%)', 'Births in the 5 years preceding the survey that are third or higher order (%)', 'Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)', 'Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any method6 (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any modern method6 (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Female sterilization (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Male sterilization (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - IUD/PPIUD (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Pill (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Condom (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Injectables (%)', 'Total Unmet need for Family Planning (Currently Married Women Age 15-49  years)7 (%)', 'Unmet need for spacing (Currently Married Women Age 15-49  years)7 (%)', 'Health worker ever talked to female non-users about family planning (%)', 'Current users ever told about side effects of current method of family planning8 (%)', 'Mothers who had an antenatal check-up in the first trimester  (for last birth in the 5 years before the survey) (%)', 'Mothers who had at least 4 antenatal care visits  (for last birth in the 5 years before the survey) (%)', 'Mothers whose last birth was protected against neonatal tetanus (for last birth in the 5 years before the survey)9 (%)', 'Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%)', 'Mothers who consumed iron folic acid for 180 days or more when they were pregnant (for last birth in the 5 years before the survey} (%)', 'Registered pregnancies for which the mother received a Mother and Child Protection (MCP) card (for last birth in the 5 years before the survey) (%)', 'Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)', 'Average out-of-pocket expenditure per delivery in a public health facility (for last birth in the 5 years before the survey) (Rs.)', 'Children born at home who were taken to a health facility for a check-up within 24 hours of birth (for last birth in the 5 years before the survey} (%)', 'Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/ other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)', 'Institutional births (in the 5 years before the survey) (%)', 'Institutional births in public facility (in the 5 years before the survey) (%)', 'Home births that were conducted by skilled health personnel  (in the 5 years before the survey)10 (%)', 'Births attended by skilled health personnel (in the 5 years before the survey)10 (%)', 'Births delivered by caesarean section (in the 5 years before the survey) (%)', 'Births in a private health facility that were delivered by caesarean section (in the 5 years before the survey) (%)', 'Births in a public health facility that were delivered by caesarean section (in the 5 years before the survey) (%)', "Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)", 'Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%)', 'Children age 12-23 months who have received BCG (%)', 'Children age 12-23 months who have received 3 doses of polio vaccine13 (%)', 'Children age 12-23 months who have received 3 doses of penta or DPT vaccine (%)', 'Children age 12-23 months who have received the first dose of measles-containing vaccine (MCV) (%)', 'Children age 24-35 months who have received a second dose of measles-containing vaccine (MCV) (%)', 'Children age 12-23 months who have received 3 doses of rotavirus vaccine14 (%)', 'Children age 12-23 months who have received 3 doses of penta or hepatitis B vaccine (%)', 'Children age 9-35 months who received a vitamin A dose in the last 6 months (%)', 'Children age 12-23 months who received most of their vaccinations in a public health facility (%)', 'Children age 12-23 months who received most of their vaccinations in a private health facility (%)', 'Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%) ', 'Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%) ', 'Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%) ', 'Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%) ', 'Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%) ', 'Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)  ', 'Children under age 3 years breastfed within one hour of birth15 (%)', 'Children under age 6 months exclusively breastfed16 (%)', 'Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%)', 'Breastfeeding children age 6-23 months receiving an adequate diet16, 17  (%)', 'Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)', 'Total children age 6-23 months receiving an adequate diet16, 17  (%)', 'Children under 5 years who are stunted (height-for-age)18 (%)', 'Children under 5 years who are wasted (weight-for-height)18 (%)', 'Children under 5 years who are severely wasted (weight-for-height)19 (%)', 'Children under 5 years who are underweight (weight-for-age)18 (%)', 'Children under 5 years who are overweight (weight-for-height)20 (%)', 'Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)', 'Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%)', 'Women (age 15-49 years) who have high risk waist-to-hip ratio (≥0.85) (%)', 'Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)', 'Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%)', 'Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%)', 'All women age 15-49 years who are anaemic22 (%)', 'All women age 15-19 years who are anaemic22 (%) ', 'Women  age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%)', 'Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%)', 'Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%)', 'Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%)', 'Men (age 15 years and above wih  very high (>160 mg/dl) Blood sugar level23 (%)', 'Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level  or taking medicine to control blood sugar level23 (%)', 'Women age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)', 'Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)', 'Women age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)', 'Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)', 'Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)', 'Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)', 'Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%)', 'Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%)', 'Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)', 'Women age 15 years and above who use any kind of tobacco (%)', 'Men age 15 years and above who use any kind of tobacco (%)', 'Women age 15 years and above who consume alcohol (%)', 'Men age 15 years and above who consume alcohol (%)']

In [29]:
#check what type of data each column contains
#like checking if each register column has number or words

print(df.dtypes)
print(f"\nTotal coulmns: {len(df.dtypes)}")

District Names                                                                               str
State/UT                                                                                     str
Number of Households surveyed                                                              int64
Number of Women age 15-49 years interviewed                                                int64
Number of Men age 15-54 years interviewed                                                  int64
                                                                                          ...
Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)    float64
Women age 15 years and above who use any kind of tobacco (%)                             float64
Men age 15 years and above who use any kind of tobacco (%)                               float64
Women age 15 years and above who consume alcohol (%)                                     float64
Men age 15 years and above who consume alcohol (%)                                       float64
Length: 109, dtype: object

Total coulmns: 109

In [30]:
#info() is like a doctor's summary report of your dataset
#shows columns, data types and how many values are missing

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Columns: 109 entries, District Names to Men age 15 years and above who consume alcohol (%)
dtypes: float64(75), int64(3), object(29), str(2)
memory usage: 615.8+ KB

In [31]:
#describe() gives you statistics for every numeric column
#min, max, average, et - al in one shot

df.describe()

,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),Population living in households with electricity (%),Population living in households with an improved drinking-water source1 (%),...,Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
count,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,...,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.00000
mean,900.502122,1024.019802,144.002829,71.507822,26.356874,1020.696139,937.990184,91.064795,96.996025,93.726054,...,16.253621,6.042518,24.759661,1.565827,0.652900,0.700495,11.614965,40.599646,2.912631,23.19075
std,69.273371,177.064999,31.953268,10.311666,5.296601,73.367114,165.625452,9.392697,4.354175,8.714690,...,4.336475,2.573082,6.768313,2.774292,1.566614,1.468252,11.943028,14.081028,6.079181,13.36201
min,213.000000,216.000000,17.000000,45.360000,15.980000,754.980000,-1261.450000,51.580000,68.350000,41.180000,...,5.290000,0.830000,10.020000,0.000000,0.000000,0.000000,0.060000,6.750000,0.000000,0.07000
25%,882.000000,911.000000,124.000000,64.395000,22.505000,969.055000,864.850000,87.030000,96.390000,92.030000,...,13.190000,4.105000,19.825000,0.190000,0.000000,0.000000,4.090000,30.420000,0.270000,13.58500
50%,908.000000,1020.000000,145.000000,71.340000,25.360000,1013.260000,930.040000,94.890000,98.650000,96.980000,...,16.250000,5.830000,24.420000,0.550000,0.210000,0.280000,7.670000,42.490000,0.500000,20.16000
75%,931.000000,1141.000000,164.000000,78.970000,29.530000,1065.530000,1014.575000,97.745000,99.515000,99.250000,...,18.845000,7.555000,28.970000,1.520000,0.500000,0.690000,14.765000,50.970000,1.710000,30.89000
max,990.000000,1621.000000,241.000000,99.160000,50.560000,1331.640000,1484.970000,100.000000,100.000000,100.000000,...,32.860000,19.460000,49.610000,23.220000,14.550000,15.840000,70.580000,80.560000,42.770000,68.38000

In [32]:
#describe() but readable -only show key colums
#round to 2 decimal places for clean reading

df.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
Number of Households surveyed,707.0,900.50,69.27,213.00,882.00,908.00,931.00,990.00
Number of Women age 15-49 years interviewed,707.0,1024.02,177.06,216.00,911.00,1020.00,1141.00,1621.00
Number of Men age 15-54 years interviewed,707.0,144.00,31.95,17.00,124.00,145.00,164.00,241.00
Female population age 6 years and above who ever attended school (%),707.0,71.51,10.31,45.36,64.40,71.34,78.97,99.16
Population below age 15 years (%),707.0,26.36,5.30,15.98,22.51,25.36,29.53,50.56
...,...,...,...,...,...,...,...,...
Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),707.0,0.70,1.47,0.00,0.00,0.28,0.69,15.84
Women age 15 years and above who use any kind of tobacco (%),707.0,11.61,11.94,0.06,4.09,7.67,14.76,70.58
Men age 15 years and above who use any kind of tobacco (%),707.0,40.60,14.08,6.75,30.42,42.49,50.97,80.56
Women age 15 years and above who consume alcohol (%),707.0,2.91,6.08,0.00,0.27,0.50,1.71,42.77
Men age 15 years and above who consume alcohol (%),707.0,23.19,13.36,0.07,13.58,20.16,30.89,68.38

In [34]:
#check how many missing values in each column

missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
     'missing count':missing,
     'missing %': missing_pct.round(2)
})

#show only columns that have missing values
print(missing_report[missing_report['missing count']>0])
print(f"\n total coulmns with missing data: {(missing >0).sum()}")

Empty DataFrame
Columns: [missing count, missing %]
Index: []

 total coulmns with missing data: 0